#!/bin/bash

###############################################################################################
##                                                                                           ##
##                       Universidad Carlos III de Madrid (UC3M)                             ##
##                                                                                           ##
##    Lightning - The simple and lightweight network simulator based on Docker containers    ##
##                                                                                           ##
##    author:       Pablo Toribio (under supervision of professor C.J. Bernardos Cano)       ##
##                                                                                           ##
##    description:  installer of the program                                                 ##
##                                                                                           ##
##    usage:        sudo ./install                                                           ##
##                                                                                           ##
###############################################################################################

# Please, feel free to modify the variable LIGHTNING_INSTALLATION_DIRECTORY accordingly
# to your system needs, but do NOT add the final slash ("/") at the end of the directory.
# A folder called "lightning" will be created inside this location in order to
# store the files and libraries needed by the program. The default value is /usr/local
LIGHTNING_INSTALLATION_DIRECTORY=/usr/local

# Please, feel free to modify the variable SYMLINK_INSTALLATION_DIRECTORY accordingly
# to your system needs, but do NOT add the final slash ("/") at the end of the directory.
# A symbolic link to the main binary (stored in LIGHTNING_INSTALLATION_DIRECTORY/lightning) 
# will be created inside this location. Please ensure this location is included in the
# PATH variable of your operating system. The default value is /usr/local/bin
SYMLINK_INSTALLATION_DIRECTORY=/usr/local/bin

# ptoribi: only root or regular users with "sudo" can install lightning 
if [[ $(logname) == "root" ]] || [[ $(whoami) == "root" ]]
then
  # ptoribi: create directory for storing the program
  mkdir -p $LIGHTNING_INSTALLATION_DIRECTORY/lightning
  # ptoribi: enter into the installer folder
  cd $(dirname $(readlink -f $0))
  # ptoribi: copy all the files but the installer, the personalized_functions file and the screenshots to that directory (and overwrite previous versions of the files)
  cp -rf $(ls | grep -vw "install\personalized_functions\screenshots") $LIGHTNING_INSTALLATION_DIRECTORY/lightning/
  # ptoribi: copy the personalized_functions file only if it is not already installed (do not overwrite)
  cp -n personalized_functions $LIGHTNING_INSTALLATION_DIRECTORY/lightning/
  # ptoribi: create symbolic link, by default: /usr/local/bin/lightning ----> /usr/local/lightning-launcher
  ln -sf $LIGHTNING_INSTALLATION_DIRECTORY/lightning/lightning-launcher $SYMLINK_INSTALLATION_DIRECTORY/lightning

  echo $(tput setaf 0)$(tput setab 2) "Lightnig was properly installed" $(tput sgr 0)
  
  # ptoribi: get the last version of the scenarios from the GitHub repository
  rm -rf $GITHUB_SCENARIOS $LIGHTNING_INSTALLATION_DIRECTORY/lightning/scenarios
  mkdir $LIGHTNING_INSTALLATION_DIRECTORY/lightning/scenarios
  source $LIGHTNING_INSTALLATION_DIRECTORY/lightning/variables.conf
  git clone $GITHUB_SCENARIOS $LIGHTNING_INSTALLATION_DIRECTORY/lightning/scenarios
  if [ $? == 0 ]
  then
    echo $(tput setaf 0)$(tput setab 2) "Scenarios were properly installed" $(tput sgr 0)
  else
    echo $(tput setaf 0)$(tput setab 1) "Error while getting scenarios from GitHub, are you connected to the internet?" $(tput sgr 0)
  fi
  
else
  echo $(tput setaf 0)$(tput setab 1) "Lightnig has to be installed as root or using "sudo"" $(tput sgr 0)
fi
