#!/bin/bash

###############################################################################################
##                                                                                           ##
##                       Universidad Carlos III de Madrid (UC3M)                             ##
##                                                                                           ##
##    Lightning - The simple and lightweight network simulator based on Docker containers    ##
##                                                                                           ##
##    author:         Pablo Toribio (under supervision of professor C.J. Bernardos Cano)     ##
##                                                                                           ##
##    project site:   https://github.com/ptoribi/lightning                                   ##
##                                                                                           ##
##    file description:  installer of the program                                            ##
##                                                                                           ##
##    usage:             sudo ./install                                                      ##
##                                                                                           ##
###############################################################################################

# Please, feel free to modify the variable LIGHTNING_INSTALLATION_DIRECTORY accordingly
# to your system needs, but do NOT add the final slash ("/") at the end of the directory.
# A folder called "lightning" will be created inside this location in order to
# store the files and libraries needed by the program. The default value is /usr/local
LIGHTNING_INSTALLATION_DIRECTORY=/usr/local

# Please, feel free to modify the variable SYMLINK_INSTALLATION_DIRECTORY accordingly
# to your system needs, but do NOT add the final slash ("/") at the end of the directory.
# A symbolic link to the main binary (stored in LIGHTNING_INSTALLATION_DIRECTORY/lightning)
# will be created inside this location. Please ensure this location is included in the
# PATH variable of your operating system. The default value is /usr/local/bin
SYMLINK_INSTALLATION_DIRECTORY=/usr/local/bin

# ptoribi: only root or regular users with "sudo" can install lightning
if [[ -n "$SUDO_USER" ]] || [[ $(whoami) == "root" ]]
then
  # ptoribi: create a directory for storing the program
  mkdir -p $LIGHTNING_INSTALLATION_DIRECTORY/lightning
  # ptoribi: enter into the installer folder
  cd $(dirname $(readlink -f $0))
  # ptoribi: copy all the files but the installer, the personalized_functions file, the README.md file, the screenshots and the xtras to that directory (and overwrite previous versions of the files if present)
  cp -rf $(ls | grep -vw "install\|personalized_functions\|README.md\|screenshots\|xtras") $LIGHTNING_INSTALLATION_DIRECTORY/lightning/
  # ptoribi: copy the personalized_functions file only if it is not already installed (do not overwrite)
  cp -n personalized_functions $LIGHTNING_INSTALLATION_DIRECTORY/lightning/
  # ptoribi: makes a backup of /etc/docker/daemon.json if present and deletes the original
  if [[ -f "/etc/docker/daemon.json" ]]; then
    cp /etc/docker/daemon.json /etc/docker/daemon.json.backup
    if [ $? == 0 ]
    then
      rm /etc/docker/daemon.json
      echo $(tput setaf 0)$(tput setab 2) "Backup of daemon.json performed: /etc/docker/daemon.json -> /etc/docker/daemon.json.backup" $(tput sgr 0)
    fi

    # ptoribi: reload the Docker configuration file
    systemctl reload docker
  fi
  
  # ptoribi: create symbolic link, by default: /usr/local/bin/lightning ----> /usr/local/lightning-launcher
  ln -sf $LIGHTNING_INSTALLATION_DIRECTORY/lightning/lightning-launcher $SYMLINK_INSTALLATION_DIRECTORY/lightning

  echo $(tput setaf 0)$(tput setab 2) "Lightning was properly installed" $(tput sgr 0)

  # ptoribi: get the last version of the scenarios from the GitHub repository
  rm -rf $GITHUB_SCENARIOS $LIGHTNING_INSTALLATION_DIRECTORY/lightning/scenarios
  mkdir $LIGHTNING_INSTALLATION_DIRECTORY/lightning/scenarios
  source $LIGHTNING_INSTALLATION_DIRECTORY/lightning/variables.conf
  git clone --depth=1 $GIT_REPO_SCENARIOS $LIGHTNING_INSTALLATION_DIRECTORY/lightning/scenarios
  if [ $? == 0 ]
  then
    echo $(tput setaf 0)$(tput setab 2) "Scenarios were properly installed" $(tput sgr 0)
  else
    echo $(tput setaf 0)$(tput setab 1) "Error while getting scenarios from GitHub, are you connected to the internet?" $(tput sgr 0)
  fi

  # ptoribi: download & install / update the Docker images from DockerHub
  docker pull $DOCKER_IMAGE_host
  docker pull $DOCKER_IMAGE_router

else
  echo $(tput setaf 0)$(tput setab 1) "Lightning has to be installed as root or using "sudo"" $(tput sgr 0)
fi
