#!/bin/bash

###############################################################################################
##                                                                                           ##
##                       Universidad Carlos III de Madrid (UC3M)                             ##
##                                                                                           ##
##    Lightning - The simple and lightweight network simulator based on Docker containers    ##
##                                                                                           ##
##    author:       Pablo Toribio (under supervision of professor C.J. Bernardos Cano)       ##
##    version:      0.7 BETA (do NOT use this program in a production environment)           ##
##                                                                                           ##
##    description:  launcher: ensures that lightning is executed with proper user            ##
##                  privileges.                                                              ##
##                                                                                           ##
##    usage:        sudo ./install                                                           ##
##                                                                                           ##
###############################################################################################

LIGHTNING_INSTALLATION_PATH=$(dirname $(readlink -f $(which lightning)))

# ptoribi: configure the console to use 256 colors
export TERM=xterm-256color
#export LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32'

# ptoribi: the purpose of "lightning-launcher" is to ensure that the main program
# is executed by a regular user with "sudo" command. If sudo has already been used
# for executing lightning-launcher, it just proceeds to execute the main one.
# Execution of the program directly as root is not supported.

# lightning (symlink) ----> lightning-launcher ----> sudo lightning (main program)

if [ $(logname)!="root" -a $(whoami)!="root" ]
then
  # I use "$@" for propagating all the arguments among scripts.
  sudo $LIGHTNING_INSTALLATION_PATH/lightning "$@"
elif [ $(logname)!="root" -a $(whoami)=="root" ]
then
  # I use "$@" for propagating all the arguments among scripts.
  $LIGHTNING_INSTALLATION_PATH/lightning "$@"
elif [ $(logname)=="root" -a $(whoami)=="root" ]
then
  echo $(tput setaf 220)[lightning-launcher]:$(tput sgr 0) $(tput setaf 0)$(tput setab 1) Execution of this program directly as root is not supported. $(tput sgr 0)
fi
