#!/bin/bash

###############################################################################################
##                                                                                           ##
##                       Universidad Carlos III de Madrid (UC3M)                             ##
##                                                                                           ##
##    Lightning - The simple and lightweight network simulator based on Docker containers    ##
##                                                                                           ##
##    author:         Pablo Toribio (under supervision of professor C.J. Bernardos Cano)     ##
##                                                                                           ##
##    project site:   https://github.com/ptoribi/lightning                                   ##
##                                                                                           ##
##    file description:  ensures that lightning is executed with proper user privileges      ##
##                       and launchs the application                                         ##
##                                                                                           ##
##    usage:             ./lightning-launcher                                                ##
##                                                                                           ##
###############################################################################################

# ptoribi: "which" will find in the path the full location of the executable, "readlink -f" will resolve all possible symbolic links and "dirname" will remove the last component (file name).
# In the default case: /usr/local/bin/lightning -> /usr/local/lightning/lightning-launcher -> /usr/local/lightning
LIGHTNING_INSTALLATION_PATH=$(dirname $(readlink -f $(which lightning)))

# ptoribi: configure the console to use 256 colors
export TERM=xterm-256color

# ptoribi: the purpose of "lightning-launcher" is to ensure that the main program
# is executed by a regular user with "sudo" command. If sudo has already been used
# for executing lightning-launcher, it just proceeds to execute the main one.
# Execution of the program directly as root is not supported.

# ptoribi: execution sequence
# lightning (symlink) ----> lightning-launcher ----> sudo lightning (main program)

if [ $(logname)!="root" -a $(whoami)!="root" ]
then
  # ptoribi: the program was executed as a regular user
  # I use "$@" for propagating all the arguments among scripts.
  sudo $LIGHTNING_INSTALLATION_PATH/lightning "$@"
elif [ $(logname)!="root" -a $(whoami)=="root" ]
then
  # ptoribi: the program was executed as a regular user with sudo
  # I use "$@" for propagating all the arguments among scripts.
  $LIGHTNING_INSTALLATION_PATH/lightning "$@"
elif [ $(logname)=="root" -a $(whoami)=="root" ]
then
  # ptoribi: the program was executed as root directly
  echo $(tput setaf 220)[lightning-launcher]:$(tput sgr 0) $(tput setaf 0)$(tput setab 1) Execution of this program directly as root is not supported. $(tput sgr 0)
fi
