#!/bin/bash

###############################################################################################
##                                                                                           ##
##                       Universidad Carlos III de Madrid (UC3M)                             ##
##                                                                                           ##
##    Lightning - The simple and lightweight network simulator based on Docker containers    ##
##                                                                                           ##
##    author:       Pablo Toribio (under supervision of professor C.J. Bernardos Cano)       ##
##    version:      0.7 BETA (do NOT use this program in a production environment)           ##
##                                                                                           ##
##    description:  updater of the program                                                   ##
##                                                                                           ##
##    usage:        not to be used directly, but summoned by "lightning" file                ##
##                                                                                           ##
###############################################################################################

LIGHTNING_INSTALLATION_PATH=$(dirname $(readlink -f $(which lightning)))
source $LIGHTNING_INSTALLATION_PATH/variables.conf

# ptoribi: update the Docker images from DockerHub
docker pull $DOCKER_IMAGE_host
docker pull $DOCKER_IMAGE_router

# ptoribi: prepare a folder in /tmp
rm -rf /tmp/lightning-tmp 
mkdir /tmp/lightning-tmp
    
# ptoribi: the last version of Lightning will be downloaded from GitHub
git clone $GITHUB /tmp/lightning-tmp

# ptoribi: the version currently installed in the system will be uninstalled
sudo $(dirname $(readlink -f $(which lightning)))/uninstall

# ptoribi: the new version will be installed
sudo /tmp/lightning-tmp/install
