#!/bin/bash

###############################################################################################
##                                                                                           ##
##                       Universidad Carlos III de Madrid (UC3M)                             ##
##                                                                                           ##
##    Lightning - The simple and lightweight network simulator based on Docker containers    ##
##                                                                                           ##
##    author:       Pablo Toribio (under supervision of professor C.J. Bernardos Cano)       ##
##                                                                                           ##
##    description:  updater of the program                                                   ##
##                                                                                           ##
##    usage:        not to be used directly, but summoned by "lightning" file                ##
##                                                                                           ##
###############################################################################################

LIGHTNING_INSTALLATION_PATH=$(dirname $(readlink -f $(which lightning)))
source $LIGHTNING_INSTALLATION_PATH/variables.conf

# ptoribi: update the Docker images from DockerHub
docker pull $DOCKER_IMAGE_host
docker pull $DOCKER_IMAGE_router

# ptoribi: prepare a folder in /tmp for saving files contained in scenarios-local
rm -rf /tmp/scenarios-local-tmp 
mkdir /tmp/scenarios-local-tmp
cp -r $LIGHTNING_INSTALLATION_PATH/scenarios-local /tmp

# ptoribi: prepare a folder in /tmp for storing GitHub temp files
rm -rf /tmp/lightning-tmp 
mkdir /tmp/lightning-tmp

# ptoribi: the last version of Lightning will be downloaded from GitHub
git clone $GITHUB /tmp/lightning-tmp

if [ $? == 0 ]
then

  SHARED_FOLDER_NAME=$(grep "SHARED_FOLDER_NAME=" $LIGHTNING_INSTALLATION_PATH/variables.conf | cut -d \" -f 2)
  if [[ ${#SHARED_FOLDER_NAME} -ne 0 ]]
  then
    echo $SHARED_FOLDER_NAME
  fi
      
      
  # ptoribi: the version currently installed in the system will be uninstalled
  $(dirname $(readlink -f $(which lightning)))/uninstall

  # ptoribi: the new version will be installed
  /tmp/lightning-tmp/install
  
  # ptoribi: restore scenarios-local
  cp -r /tmp/scenarios-local-tmp $LIGHTNING_INSTALLATION_PATH
  
else
  echo $(tput setaf 0)$(tput setab 1) "Error while getting lightning from GitHub, are you connected to the internet?" $(tput sgr 0)
fi
